const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event7_Act1,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event8_Act1,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event10_Act2,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event12_Act1,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event14_Act1,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event16_Act1,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event18_Act1,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event20_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsClockwiseFrom,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event24_Act1,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event30_Act1,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetFullscreenQuality
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{GALAXY_BG: 0},
	{Projétil: 0},
	{PLANETA_ANÉIS: 0},
	{PLANETA_AMARELO: 0},
	{LUA: 0},
	{PLANETA_LARANJA: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{NAVE_JOGADOR: 0},
	{Teclado: 0},
	{TIRO: 0},
	{NAVE_INIMIGO: 0},
	{Piscar: 0},
	{ENERGIA: 0},
	{BOMBA: 0},
	{PlanoDeFundoEmBlocos: 0},
	{START: 0},
	{Mouse: 0},
	{MoverPara: 0},
	{GENERAL: 0},
	{CHEFÃO: 0},
	{CONTADOR_VIDA: 0},
	{CONTADOR_ENERGIA: 0},
	{CONTADOR_DESTRUIDOS: 0},
	{CONTADOR_PONTOS: 0},
	{VIDA_TEXTO: 0},
	{ENERGIA_TEXTO: 0},
	{PONTOS_TEXTO: 0},
	{DESTRUIDOS_TEXTO: 0},
	{CONTADOR_GENERAL: 0},
	{VIDA_GENERAL_TEXTO: 0},
	{CONTADOR_CHEFAO: 0},
	{CHEFAO_HP: 0},
	{AGAIN: 0},
	{OVER: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PLAAGAINWIN: 0},
	{WIN: 0},
	{ENERGIAA: 0},
	{DERROTADOS: 0},
	{HP: 0},
	{PONTOS: 0},
	{PODE_ATIRAR: 0},
	{GENERAL_HP: 0},
	{GENERAL_ATIVO: 0}
];

self.InstanceType = {
	GALAXY_BG: class extends self.ITiledBackgroundInstance {},
	PLANETA_ANÉIS: class extends self.ISpriteInstance {},
	PLANETA_AMARELO: class extends self.ISpriteInstance {},
	LUA: class extends self.ISpriteInstance {},
	PLANETA_LARANJA: class extends self.ISpriteInstance {},
	NAVE_JOGADOR: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	TIRO: class extends self.ISpriteInstance {},
	NAVE_INIMIGO: class extends self.ISpriteInstance {},
	ENERGIA: class extends self.ISpriteInstance {},
	BOMBA: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	START: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	GENERAL: class extends self.ISpriteInstance {},
	CHEFÃO: class extends self.ISpriteInstance {},
	CONTADOR_VIDA: class extends self.ISpriteInstance {},
	CONTADOR_ENERGIA: class extends self.ISpriteInstance {},
	CONTADOR_DESTRUIDOS: class extends self.ISpriteInstance {},
	CONTADOR_PONTOS: class extends self.ISpriteInstance {},
	VIDA_TEXTO: class extends self.ITextInstance {},
	ENERGIA_TEXTO: class extends self.ITextInstance {},
	PONTOS_TEXTO: class extends self.ITextInstance {},
	DESTRUIDOS_TEXTO: class extends self.ITextInstance {},
	CONTADOR_GENERAL: class extends self.ISpriteInstance {},
	VIDA_GENERAL_TEXTO: class extends self.ITextInstance {},
	CONTADOR_CHEFAO: class extends self.ISpriteInstance {},
	CHEFAO_HP: class extends self.ITextInstance {},
	AGAIN: class extends self.ISpriteInstance {},
	OVER: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PLAAGAINWIN: class extends self.ISpriteInstance {},
	WIN: class extends self.ISpriteInstance {}
}