const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Y,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event8_Act1,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event10_Act2,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event15_Act1,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{GALAXY_BG: 0},
	{Projétil: 0},
	{PLANETA_ANÉIS: 0},
	{PLANETA_AMARELO: 0},
	{LUA: 0},
	{PLANETA_LARANJA: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{NAVE_JOGADOR: 0},
	{Teclado: 0},
	{TIRO: 0},
	{NAVE_INIMIGO: 0},
	{Piscar: 0},
	{ENERGIA: 0},
	{BOMBA: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{Mouse: 0}
];

self.InstanceType = {
	GALAXY_BG: class extends self.ITiledBackgroundInstance {},
	PLANETA_ANÉIS: class extends self.ISpriteInstance {},
	PLANETA_AMARELO: class extends self.ISpriteInstance {},
	LUA: class extends self.ISpriteInstance {},
	PLANETA_LARANJA: class extends self.ISpriteInstance {},
	NAVE_JOGADOR: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	TIRO: class extends self.ISpriteInstance {},
	NAVE_INIMIGO: class extends self.ISpriteInstance {},
	ENERGIA: class extends self.ISpriteInstance {},
	BOMBA: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {}
}